openapi: 3.0.0
info:
  title: WASAPhoto
  version: "0.1.0"
  contact:
    name: Alessio Bandiera
    email: bandiera.1985878@studenti.uniroma1.it
    url: https://github.com/ph04
  license:
    name: TODO
  description: |-
    Each user will be presented with a stream of photos in reverse chronological order, with information
    about when it was uploaded (date and time) and how many likes and comments it has. 
    
    Users can place
    (and later remove) a “like” to photos from other users. Also, users can add comments to any photo
    (even those uploaded by themself). Comments can be removed by the author only. Users can ban other users.
    If Alice (user) bans Eve (user), Eve won’t be able tosee any information about Alice. Alice can decide to
    remove the ban at any moment.
    
    Users will have their own personal profiles. The personal profile page for
    user detail contains user’s photos (in reverse chronological order), their followers and following, and how many
    photos have been uploaded. Each user can change his/her own username, upload photos,
    remove photos, and follow/unfollow other users. Removal of a photo will also remove likes and comments.

tags:
  - name : "Login"
    description: "Endpoints for the user login"
  - name: "Ban"
    description: "Endpoints for banning users"
  - name: "Follow"
    description: "Endpoints for folllowing users"
  - name: "Photos"
    description: "Endpoints for uploading photos"
  - name: "Like"
    description: "Endpoints for liking photos"
  - name: "Comment"
    description: "Endpoints for commenting photos"

paths:
  /session:
    post:
      tags: ["Login"]
      summary: Logs in the user
      description: |-
        TODO
      operationId: doLogin
      requestBody:
        description: User details
        required: true
        content:
          application/json:
            schema: { $ref: "#/components/schemas/user" }
      responses:
        '201':
          description: User log-in action successful
  
  /user/{uid}/ban:
    parameters:
      - { $ref: "#/components/parameters/uid" }
    
    get:
      security:
        - bearerAuth: []
      tags: ["Ban"]
      summary: List of banned users
      description: |-
        TODO
      operationId: getBanList
      responses:
        "200":
          description: TODO
          content:
            application/json:
              schema: { $ref: "#/components/schemas/userlist" }
  
  /{uid}/ban/{banneduid}:
    parameters:
      - { $ref: "#/components/parameters/uid" }
      - { $ref: "#/components/parameters/banneduid" }
    
    put:
      security:
        - bearerAuth: []
      tags: ["Ban"]
      summary: Ban a user
      description: |-
        TODO
      operationId: banUser
      responses:
        "200":
          description: User banned successfully
      
    delete:
      security:
        - bearerAuth: []
      tags: ["Ban"]
      summary: Unban a user
      description: |-
        TODO
      operationId: unbanUser
      responses:
        "200":
          description: User unbanned successfully
        "400": { $ref: "#/components/responses/BadRequest" }
        "401": { $ref: "#/components/responses/Unauthorized" }
        "500": { $ref: "#/components/responses/InternalServerError" }
  
  /{uid}/follow/{followuid}:
    parameters:
      - { $ref: "#/components/parameters/uid" }
      - { $ref: "#/components/parameters/followuid" }
      
    put:
      security:
        - bearerAuth: []
      tags: ["Follow"]
      summary: Follow a user  
      description: |-
        TODO
      operationId: followUser
      responses:
        "200":
          description: User followed successfully
      
    delete:
      security:
        - bearerAuth: []
      tags: ["Follow"]
      summary: Unnfollow a user
      description: |-
        TODO
      operationId: unfollowUser
      responses:
        "200":
          description: User unfollowed successfully
  
  /{uid}/followers:
    parameters:
      - { $ref: "#/components/parameters/uid" }
    
    get:
      security:
        - bearerAuth: []
      tags: ["Follow"]
      summary: List of user followers
      operationId: getFollowers
      responses:
        "200":
          description: TODO
          content:
            application/json:
              schema: { $ref: "#/components/schemas/userlist" }
  
  /{uid}/following:
    parameters:
      - { $ref: "#/components/parameters/uid" }
    
    get:
      security:
        - bearerAuth: []
      tags: ["Follow"]
      summary: List of users followed
      operationId: getFollowing
      responses:
        "200":
          description: TODO
          content:
            application/json:
              schema: { $ref: "#/components/schemas/userlist" }
  
  /{uid}/upload:
    parameters:
      - { $ref: "#/components/parameters/uid" }
    
    post:
      security:
        - bearerAuth: []
      tags: ["Photos"]
      summary: Upload a photo
      description: |-
        TODO
      operationId: uploadPhoto
      requestBody:
        description: The photo to be uploaded
        required: true
        content:
          application/json:
            schema: { $ref: "#/components/schemas/photo" }
      responses:
        "200":
          description: Photo uploaded successfully
  
  /{uid}/{photoid}:
    parameters:
      - { $ref: "#/components/parameters/uid" }
      - { $ref: "#/components/parameters/photoid" }
    
    delete:
      security:
        - bearerAuth: []
      tags: ["Photos"]
      summary: Delete a photo
      description: |-
        TODO
      operationId: deletePhoto
      responses:
        "200":
          description: Photo deleted successfully
  
  /{uid}/{photoid}/like/{likeuid}:
    parameters:
      - { $ref: "#/components/parameters/uid" }
      - { $ref: "#/components/parameters/photoid" }
      - { $ref: "#/components/parameters/likeuid" }
      
    put:
      security:
        - bearerAuth: []
      tags: ["Like"]
      summary: Like a photo
      operationId: likePhoto
      responses:
        "200":
          description: Photo liked successfully
    
    delete:
      security:
        - bearerAuth: []
      tags: ["Like"]
      summary: Remove a like from a photo
      operationId: unlikePhoto
      responses:
        "200":
          description: Like removed successfully
  
  /{uid}/{photoid}/comment:
    parameters:
      - { $ref: "#/components/parameters/uid" }
      - { $ref: "#/components/parameters/photoid" }
      
    post:
      security:
        - bearerAuth: []
      tags: ["Comment"]
      summary: Comment a photo
      operationId: commentPhoto
      requestBody:
        description: The comment to be posted
        required: true
        content:
          application/json:
            schema: { $ref: "#/components/schemas/comment" }
      responses:
        "200":
          description: Comment posted successfully
  
  /{uid}/{photoid}/{commentid}:
    parameters:
      - { $ref: "#/components/parameters/uid" }
      - { $ref: "#/components/parameters/photoid" }
      - { $ref: "#/components/parameters/commentid" }
    
    delete:
      security:
        - bearerAuth: []
      tags: ["Comment"]
      summary: Remove a comment from a photo
      operationId: uncommentPhoto
      responses:
        "200":
          description: Comment removed successfully

  /{uid}:
    parameters:
      - { $ref: "#/components/parameters/uid" }
    
    get:
      security:
        - bearerAuth: []
      tags: ["User"]
      summary: Get a user profile information
      operationId: getUserProfile
      responses:
        "200":
          description: The requested user profile information
          content:
            application/json:
              schema: { $ref: "#/components/schemas/profile" }

  /{uid}/username:
    parameters:
      - { $ref: "#/components/parameters/uid" }
    
    put:
      security:
        - bearerAuth: []
      tags: ["User"]
      summary: Change username
      operationId: setMyUserName
      requestBody:
        description: The new username
        required: true
        content:
          application/json:
            schema: { $ref: "#/components/schemas/user" }
      responses:
        "200":
          description: TODO

  /{uid}/stream:
    parameters:
      - { $ref: "#/components/parameters/uid" }
    
    get:
      security:
        - bearerAuth: []
      tags: ["Stream"]
      summary: Retrieve the user stream
      operationId: getMyStream
      responses:
        "200":
          description: The user stream
          content:
            application/json:
              schema: { $ref: "#/components/schemas/stream" }

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  
  schemas:
    user:
      title: User
      description: The component that represents a user
      type: object
      properties:
        name:
          type: string
          example: Maria
          pattern: 'ˆ.*?$'
          minLength: 3
          maxLength: 16
    
    photo:
      title: Photo
      description: The component that represents a photo
      type: object
      properties:
        user: { $ref: "#/components/schemas/user" }
        id:
          type: integer
          description: TODO
          example: 1234
        url:
          type: string
          description: TODO
          example: "TODO"
        date:
          type: string
          description: TODO
          example: "TODO"
        likeCounter:
          type: integer
          description: TODO
          minimum: 0
          example: 1000
        commentCounter:
          type: integer
          description: TODO
          minimum: 0
          example: 1000
    
    comment:
      title: Comment
      description: The component that represents a comment
      type: object
      properties:
        user: { $ref: "#/components/schemas/user" }
        id:
          type: integer
          description: TODO
          example: 1234
        commentBody:
          type: string
          description: TODO
          example: TODO
  
    profile:
      title: Profile
      description: The components that represents a user profile
      type: object
      properties:
        user: { $ref: "#/components/schemas/user" }
        photoCounter:
          type: integer
          description: TODO
          example: 1000
        followers:
          type: array
          items: { $ref: "#/components/schemas/user" }
          description: TODO
        following:
          type: array
          items: { $ref: "#/components/schemas/user" }
          description: TODO
        photos:
          type: array
          items: { $ref: "#/components/schemas/photo" }
  
    stream:
      title: Stream
      description: The components that represents the user stream
      type: array
      items: { $ref: "#/components/schemas/photo" }
    
    userlist:
      title: UserList
      description: TODO
      type: array
      items: { $ref: "#/components/schemas/user" }
  
  parameters:
    uid:
      name: uid
      in: path
      description: The parameter that represents the user performing the operation
      required: true
      schema: { $ref: "#/components/schemas/user" }
    banneduid:
      name: banneduid
      in: path
      description: The parameter that represents the banned user
      required: true
      schema: { $ref: "#/components/schemas/user" }
    followuid:
      name: followuid
      in: path
      description: The parameter that represents the user to be followed
      required: true
      schema: { $ref: "#/components/schemas/user" }
    likeuid:
      name: likeuid
      in: path
      description: TODO
      required: true
      schema: { $ref: "#/components/schemas/user" }
    photoid:
      name: photoid
      in: path
      description: The parameter that represents the photo
      required: true
      schema: { $ref: "#/components/schemas/photo" }
    commentid:
      name: commentid
      in: path
      description: TODO
      required: true
      schema: { $ref: "#/components/schemas/comment" }
  
  responses:
    BadRequest:
      description: TODO
    Unauthorized:
      description: TODO
    InternalServerError:
      description: TODO
