extends: '@ibm-cloud/openapi-ruleset'
rules:
  ibm-major-version-in-path: off
  oas3-api-servers: off
  ibm-no-ambiguous-paths: off
  ibm-operationid-casing-convention: off
  ibm-operationid-naming-convention: off
  oas3-valid-schema-example: off
  ibm-success-response-example: off # TODO RIMUOVI
  ibm-request-and-response-content: off # TODO RIMUOVI